name = "WeightlessNeuralNetwork"
uuid = "d596992c-e674-49a1-b051-cc7fd5f73dfa"
authors = ["Diego Carvalho <d.carvalho@ieee.org>"]
version = "0.1.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
